### ISSUE TITLE
How Me Install this jsnes

### ISSUE THREAD

**Issue by Noahbob2233** [bfirsh/jsnes#109]
I need help installing this to me site. I use cpanel and their is not a tutorial on it. I don't know how to do it. I want it to look like the one the creator has. I don't know if this github stuff will get me that end result. I think that is the demo of this. I don't know and I need help.

**Comment by bfirsh** [comment]
Hi! You’re looking for this:

https://github.com/bfirsh/jsnes-web

It’s not straight forward because there is a build process but hopefully you can figure it out. If you install Node.js and Yarn, then run `yarn build` it’ll build the emulator on my website. The code you can upload to cPanel and so on is in the `build/` directory after you have run that command.

Good luck!

**Comment by alexcrz** [comment]
Hi! I've done all the steps, directly on my hosting, got also the build folder, but when I open the index.html file in that folder, I just get a black page, and if I inspect the page, I don't get any error.

**Comment by raousoft** [comment]
> Hi! I've done all the steps, directly on my hosting, got also the build folder, but when I open the index.html file in that folder, I just get a black page, and if I inspect the page, I don't get any error.

I have the same problem , a blank white page with only page title showing up :/
