### ISSUE TITLE
Add Webkit Web Audio Support

### ISSUE THREAD

**Issue by ghost** [bfirsh/jsnes#7]
I see you've already added moz audio and a flash fallback for audio support.
There's an api for macintosh chrome and experimental builds of safari that is similar to moz audio.
I thought you should know about http://chromium.googlecode.com/svn/trunk/samples/audio/index.html
To enable web audio support in chrome you have to enable it in about:flags

**Comment by davidmarkclements** [comment]
I've been experimenting with the WebAudio API and I have a PoC which gets the sound syncing correctly. 

However I'm struggling with sound quality, I'm pretty certain this is because I'm not converting
from Arrays of numbers between 0-255 (e.g. representing bytes, essentially the equivalent of Uint8Arrays) and Float32Arrays (which is what `buffer.getChannelData` returns).

Also the volume is super high, this can be easily adjusted by applying a ratio to the output, but we shouldn't have to do that. 

Here's my efforts so far (WARNING PUT VOLUME TO MINIMUM BEFORE TESTING): 

https://github.com/davidmarkclements/jsnes/commit/8a4a2244255114aa03d5da2ac0e54ddfb7aa1824#diff-478c5384d0b4a5ca4c1a8e27f9a68c08

The closest sound quality I could get is by passing samples array to Uint16Array, then passing the resulting ArrayBuffer into Float32Array, which is copied (using `set`) into the left and right channels there's probably a better way

It's quite likely that @bfirsh will know exactly how to convert to Float32Array but it seems like he's lost interest :(

**Comment by davidmarkclements** [comment]
One thought is that papu.js actually mixes the right and left channels together with bitwise ops, if we could figure how to untangle that, it might be easier (and .. actually much cooler) to send each channels audio seperately

**Comment by webdevbyjoss** [comment]
hey guys, I think I've figured out the proper way to split the stereo channels and get the crystal clear sound. Check out here: https://github.com/bfirsh/jsnes/pull/45

**Comment by webdevbyjoss** [comment]
now in dynamicaudio.js https://github.com/bfirsh/dynamicaudio.js/pull/7

**Comment by bfirsh** [comment]
Wooot. Thanks @webdevbyjoss.

Now live: https://fir.sh/projects/jsnes/
